apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  onload-version: "0.2"
  socket-name: vnfNIC
  resource-name: paloaltonetworks.com/vnfdevice
  k8s-api: https://<ClusterIP>
  node-label-onload-version: device.vnf.onload-version
  vnf-max-instances: "8"
  k8s-passwd: <cluster credentials password>
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: vnf-device-plugin
  namespace: default
  labels:
    tier: node
spec:
  template:
    metadata:
      labels:
        tier: node
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      containers:
      - name: vnfdevice
        image: gcr.io/gcp-eng-dev/vnfdevice:0.0.1
        imagePullPolicy: Always
        securityContext:
          privileged: true
          capabilities:
            add: ["ALL"]
        command: ["./start.sh"]
        env:
        - name: ONLOAD_VERSION
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: onload-version
        - name: SOCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: socket-name
        - name: RESOURCE_NAME
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: resource-name
        - name: K8S_API
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: k8s-api
        - name: NODE_LABEL_ONLOAD_VERSION
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: node-label-onload-version
        - name: VNF_MAX_INSTANCES
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: vnf-max-instances
        - name: K8S_PASSWD
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: k8s-passwd
        volumeMounts:
          - mountPath: /gopath/run
            name: docker
          - mountPath: /gopath/proc
            name: proc
          - mountPath: "/var/lib/kubelet/device-plugins"
            name: device-plugins
          - name: varlog
            mountPath: /var/log/vnf
          - name: varrun
            mountPath: /var/run/vnf
      volumes:
        - name: docker
          hostPath:
            path: /var/run
        - name: proc
          hostPath:
            path: /proc
        - name: device-plugins
          hostPath:
            path: "/var/lib/kubelet/device-plugins"
        - name: varlog
          hostPath:
            path: /var/log/vnf
        - name: varrun
          hostPath:
            path: /var/run/vnf